layout: {zmk_keyboard: corne, layout_name: foostan_corne_6col_layout}
layers:
  Default:
  - [TAB, Q, W, E, R, T, Y, U, I, O, P, '-']
  - - LCTRL
    - {t: A, h: LGUI}
    - {t: S, h: LALT}
    - {t: D, h: LSHFT}
    - {t: F, h: LCTRL}
    - G
    - H
    - {t: J, h: LCTRL}
    - {t: K, h: LSHFT}
    - {t: L, h: LALT}
    - {t: ;, h: LGUI}
    - ''''
  - - {t: '&caps_word', h: LSHFT}
    - Z
    - X
    - C
    - V
    - B
    - N
    - M
    - ','
    - .
    - /
    - RSHFT
  - - DEL
    - {t: BSPC, h: Lower}
    - {t: SPACE, h: Nav}
    - RET
    - {t: BSPC, h: Raise}
    - INS
  Lower:
  - - '&swap'
    - '1'
    - '2'
    - '3'
    - '4'
    - '5'
    - '6'
    - '7'
    - '8'
    - '9'
    - '0'
    - {t: ▽, type: trans}
  - ['`', '!', '@', '#', $, '%', ^, '&', '*', (, ), '~']
  - - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - Ctl+Z
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
  - - {t: ▽, type: trans}
    - {type: held}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
  Raise:
  - - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - F7
    - F8
    - F9
    - F12
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
  - - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - F4
    - F5
    - F6
    - F11
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
  - - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - F1
    - F2
    - F3
    - F10
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
  - - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {type: held}
    - {t: ▽, type: trans}
  Nav:
  - - '&swap'
    - PG UP
    - HOME
    - UP
    - END
    - RET
    - '7'
    - '8'
    - '9'
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
  - - '&ctrl_h'
    - PG DN
    - LEFT
    - DOWN
    - RIGHT
    - BSPC
    - '4'
    - '5'
    - '6'
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
  - - '&shift_h'
    - {t: ▽, type: trans}
    - BSPC
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - DEL
    - '1'
    - '2'
    - '3'
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
  - - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {type: held}
    - {t: ▽, type: trans}
    - '0'
    - .
combos:
- p: [36, 24]
  k: '&bootloader'
  l: [Default]
- p: [26, 28]
  k: Ctl+X
  l: [Default, Nav]
- p: [26, 27]
  k: Ctl+C
  l: [Default, Nav]
- p: [27, 28]
  k: Ctl+V
  l: [Default, Nav]
- p: [7, 8]
  k: {t: (, s: )}
  l: [Default]
- p: [19, 20]
  k: {t: '[', s: ']'}
  l: [Default]
- p: [31, 32]
  k: {t: '{', s: '}'}
  l: [Default]
- p: [6, 7]
  k: {t: <, s: '>'}
  l: [Default]
- p: [18, 19]
  k: {t: '-', s: _}
  l: [Default]
- p: [30, 31]
  k: {t: +, s: '='}
  l: [Default]
- p: [33, 34]
  k: {t: \, s: '|'}
  l: [Default]
- p: [0, 1]
  k: ESC
  l: [Default]
