# CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_POINTING=y


# CONFIG_LV_Z_VDB_SIZE=32

CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

CONFIG_DONGLE_SCREEN_IDLE_TIMEOUT_S=30
# windows icon for gui key
CONFIG_DONGLE_SCREEN_SYSTEM_ICON=1
CONFIG_DONGLE_SCREEN_WPM_ACTIVE=n
