layout: {zmk_keyboard: lily58}
layers:
  Default:
  - [ESC, '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '`']
  - [TAB, Q, W, E, R, T, Y, U, I, O, P, '-']
  - - LCTRL
    - {t: A, h: LGUI}
    - {t: S, h: LALT}
    - {t: D, h: LSHFT}
    - {t: F, h: LCTRL}
    - G
    - H
    - {t: J, h: LCTRL}
    - {t: K, h: LSHFT}
    - {t: L, h: LALT}
    - {t: ;, h: LGUI}
    - ''''
  - - {t: '&caps_word', h: LSHFT}
    - Z
    - X
    - C
    - V
    - B
    - '['
    - ']'
    - N
    - M
    - ','
    - .
  - - /
    - RSHFT
    - LGUI
    - DEL
    - {t: BSPC, h: Lower}
    - {t: SPACE, h: Nav}
    - RET
    - {t: BSPC, h: Raise}
    - INS
    - PSCRN
  Lower:
  - - BT CLR
    - {t: BT, h: '0'}
    - {t: BT, h: '1'}
    - {t: BT, h: '2'}
    - {t: BT, h: '3'}
    - {t: BT, h: '4'}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
  - - '&swap'
    - '1'
    - '2'
    - '3'
    - '4'
    - '5'
    - '6'
    - '7'
    - '8'
    - '9'
    - '0'
    - {t: ▽, type: trans}
  - ['`', '!', '@', '#', $, '%', ^, '&', '*', (, ), '~']
  - - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - Ctl+Z
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
  - - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {type: held}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
  Raise:
  - - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
  - - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - F7
    - F8
    - F9
    - F12
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
  - - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - F4
    - F5
    - F6
    - F11
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
  - - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - F1
    - F2
    - F3
    - F10
  - - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {type: held}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
  Nav:
  - - '&bootloader'
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
  - - '&swap'
    - PG UP
    - HOME
    - UP
    - END
    - RET
    - '7'
    - '8'
    - '9'
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
  - - '&ctrl_h'
    - PG DN
    - LEFT
    - DOWN
    - RIGHT
    - BSPC
    - '4'
    - '5'
    - '6'
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
  - - '&shift_h'
    - {t: ▽, type: trans}
    - BSPC
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - DEL
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - '1'
    - '2'
    - '3'
    - {t: ▽, type: trans}
  - - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {type: held}
    - {t: ▽, type: trans}
    - '0'
    - .
    - {t: ▽, type: trans}
combos:
- p: [51, 36]
  k: '&bootloader'
  l: [Default]
- p: [38, 40]
  k: Ctl+X
  l: [Default, Nav]
- p: [38, 39]
  k: Ctl+C
  l: [Default, Nav]
- p: [39, 40]
  k: Ctl+V
  l: [Default, Nav]
- p: [19, 20]
  k: {t: (, s: )}
  l: [Default]
- p: [31, 32]
  k: {t: '[', s: ']'}
  l: [Default]
- p: [45, 46]
  k: {t: '{', s: '}'}
  l: [Default]
- p: [18, 19]
  k: {t: <, s: '>'}
  l: [Default]
- p: [30, 31]
  k: {t: '-', s: _}
  l: [Default]
- p: [44, 45]
  k: {t: +, s: '='}
  l: [Default]
- p: [47, 48]
  k: {t: \, s: '|'}
  l: [Default]
