manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: theor
      url-base: https://github.com/theor
    - name: urob
      url-base: https://github.com/urob
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-tri-state
      remote: urob
      revision: main
    # - name: zmk-display
    #   remote: theor
    #   # This points to a west manifest file in the remote module for further imports
    #   import: west.yml
  self:
    path: lily-config
    # self:
      # import: zmk-display
